name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build and publish frontend to Docker Registry
    runs-on: ubuntu-latest
    env:
      frontend: ${{secrets.DOCKERHUB_USERNAME}}/kladnitsky-ru-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add SHORT_SHA
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend}}:latest
          cache-from: type=registry,ref=${{env.frontend}}:latest
          cache-to: type=inline
          platforms: linux/x86_64
          build-args: |
            VITE_SHA=${{env.SHORT_SHA}}

  deploy:
    name: Deploy to production
    runs-on: self-hosted
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build service
        run: docker compose -f docker-compose.prod.yml build --parallel

      - name: Stop service
        run: docker compose -f docker-compose.prod.yml down

      - name: Start service
        run: docker compose -f docker-compose.prod.yml up -d
