name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build service
        run: docker compose -f docker-compose.prod.yml build --parallel

      - name: Stop service
        run: docker compose -f docker-compose.prod.yml down

      - name: Start service
        run: docker compose -f docker-compose.prod.yml up -d
