name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: self-hosted
    steps:
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_VERSION: ${{ secrets.SHORT_SHA }}
          file_name: .env
          fail_on_empty: false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build service
        run: docker compose -f docker-compose.prod.yml --env-file .env build --parallel

      - name: Stop service
        run: docker compose -f docker-compose.prod.yml down

      - name: Start service
        run: docker compose -f docker-compose.prod.yml --env-file .env up -d
